CREATE TABLE "public"."agent_experience"
(
    "id"             int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "agent_id"       int4         NOT NULL DEFAULT 0,
    "application_id" int4         NOT NULL DEFAULT 0,
    "create_time"    timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "config_data"    jsonb        NOT NULL DEFAULT '{}'::json,
    CONSTRAINT "agent_experience_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_experience"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_experience"."id" IS '主键';

COMMENT ON COLUMN "public"."agent_experience"."agent_id" IS '智能体id';

COMMENT ON COLUMN "public"."agent_experience"."application_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_experience"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_experience"."config_data" IS '配置数据';

COMMENT ON TABLE "public"."agent_experience" IS '智能体-体验';



CREATE TABLE "public"."agent_publish_history"
(
    "id"             int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "agent_id"       int4         NOT NULL DEFAULT 0,
    "application_id" int4         NOT NULL DEFAULT 0,
    "create_time"    timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "version"        int4         NOT NULL DEFAULT 1,
    "config_data"    jsonb        NOT NULL DEFAULT '{}'::json,
    CONSTRAINT "agent_publish_history_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_publish_history"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_publish_history"."id" IS '主键';

COMMENT ON COLUMN "public"."agent_publish_history"."agent_id" IS '智能体id';

COMMENT ON COLUMN "public"."agent_publish_history"."application_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_publish_history"."create_time" IS '发布时间';

COMMENT ON COLUMN "public"."agent_publish_history"."version" IS '版本号';

COMMENT ON COLUMN "public"."agent_publish_history"."config_data" IS '发布的数据';

COMMENT ON TABLE "public"."agent_publish_history" IS '智能体-发布历史';


