CREATE TABLE "public"."workflow_runs"
(
    "id"               int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "tenant_id"        varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "app_id"           int4                                        NOT NULL,
    "workflow_id"      int4                                        NOT NULL,
    "type"             varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "triggered_from"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "version"          varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "graph"            text COLLATE "pg_catalog"."default",
    "inputs"           text COLLATE "pg_catalog"."default",
    "status"           varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "outputs"          text COLLATE "pg_catalog"."default"                  DEFAULT '{}'::text,
    "error"            text COLLATE "pg_catalog"."default",
    "elapsed_time"     float8                                      NOT NULL DEFAULT 0,
    "total_tokens"     int8                                                 DEFAULT 0,
    "total_steps"      int4                                                 DEFAULT 0,
    "exceptions_count" int4                                                 DEFAULT 0,
    "created_by"       int4                                        NOT NULL,
    "created_at"       timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at"      timestamp(6),
    "workflow_run_id"  varchar(255) COLLATE "pg_catalog"."default",
    CONSTRAINT "workflow_runs_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."workflow_runs"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."workflow_runs"."id" IS '运行ID，主键';

COMMENT ON COLUMN "public"."workflow_runs"."tenant_id" IS '工作空间ID，用于多租户隔离';

COMMENT ON COLUMN "public"."workflow_runs"."app_id" IS '应用ID';

COMMENT ON COLUMN "public"."workflow_runs"."workflow_id" IS '工作流ID';

COMMENT ON COLUMN "public"."workflow_runs"."type" IS '工作流类型';

COMMENT ON COLUMN "public"."workflow_runs"."triggered_from" IS '触发来源: debugging表示画布调试, app-run表示(已发布)应用执行';

COMMENT ON COLUMN "public"."workflow_runs"."version" IS '版本';

COMMENT ON COLUMN "public"."workflow_runs"."graph" IS '工作流画布配置(JSON格式)';

COMMENT ON COLUMN "public"."workflow_runs"."inputs" IS '输入参数';

COMMENT ON COLUMN "public"."workflow_runs"."status" IS '执行状态: running/succeeded/failed/stopped';

COMMENT ON COLUMN "public"."workflow_runs"."outputs" IS '输出内容(可选)';

COMMENT ON COLUMN "public"."workflow_runs"."error" IS '错误原因(可选)';

COMMENT ON COLUMN "public"."workflow_runs"."elapsed_time" IS '时间消耗(秒)(可选)';

COMMENT ON COLUMN "public"."workflow_runs"."total_tokens" IS '使用的总token数(可选)';

COMMENT ON COLUMN "public"."workflow_runs"."total_steps" IS '总步骤数(冗余字段)，默认为0';

COMMENT ON COLUMN "public"."workflow_runs"."exceptions_count" IS '异常数量';

COMMENT ON COLUMN "public"."workflow_runs"."created_by" IS '创建人';

COMMENT ON COLUMN "public"."workflow_runs"."created_at" IS '创建时间';

COMMENT ON COLUMN "public"."workflow_runs"."finished_at" IS '运行结束时间';

COMMENT ON COLUMN "public"."workflow_runs"."workflow_run_id" IS '运行id';

COMMENT ON TABLE "public"."workflow_runs" IS '工作流运行表，存储工作流的整体运行信息';