ALTER TABLE "public"."agent_info"
    ADD COLUMN "short_term_memory_rounds" int4         NOT NULL DEFAULT 5,
    ADD COLUMN "long_term_memory_enabled" bool         NOT NULL DEFAULT false,
    ADD COLUMN "long_term_memory_type"    varchar(100) NOT NULL DEFAULT '',
    ADD COLUMN "long_term_memory_expired" int4         NOT NULL DEFAULT 0,
    ADD COLUMN "create_by"                int4         NOT NULL DEFAULT 1;

COMMENT ON COLUMN "public"."agent_info"."short_term_memory_rounds" IS '短期记忆对话轮数';

COMMENT ON COLUMN "public"."agent_info"."long_term_memory_enabled" IS '长期记忆是否开启';

COMMENT ON COLUMN "public"."agent_info"."long_term_memory_type" IS '长期记忆类型  always永久有效，custom自定义';

COMMENT ON COLUMN "public"."agent_info"."long_term_memory_expired" IS '长期记忆有效期（xx天过期）';

COMMENT ON COLUMN "public"."agent_info"."create_by" IS '创建人';


/*
 创建人更新为application表中的create_by
 */
UPDATE agent_info
SET create_by = application.create_by
FROM application
WHERE agent_info.application_id = application.id;

/**
  长期记忆表
 */
CREATE TABLE "public"."agent_long_term_memory"
(
    "id"             int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "application_id" int4                                        NOT NULL DEFAULT 0,
    "user_id"        int4                                        NOT NULL DEFAULT 1,
    "create_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "content"        varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "agent_id"       int4                                        NOT NULL DEFAULT 0,
    "vector"         "public"."vector"                           NOT NULL,
    CONSTRAINT "agent_long_term_memory_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_long_term_memory"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_long_term_memory"."id" IS '主键id';

COMMENT ON COLUMN "public"."agent_long_term_memory"."application_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_long_term_memory"."user_id" IS '创建人';

COMMENT ON COLUMN "public"."agent_long_term_memory"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_long_term_memory"."content" IS '记忆描述';

COMMENT ON COLUMN "public"."agent_long_term_memory"."agent_id" IS '智能体id';

COMMENT ON COLUMN "public"."agent_long_term_memory"."vector" IS '向量';

COMMENT ON TABLE "public"."agent_long_term_memory" IS '智能体长期记忆';