ALTER TABLE "public"."workflow_runs"
    ADD COLUMN "run_type" varchar(255) NOT NULL DEFAULT 'draft';
COMMENT ON COLUMN "public"."workflow_runs"."run_type" IS '运行类型 draft测试版 published发布版 experience体验版  ';

CREATE TABLE "public"."workflows_publish_history"
(
    "id"                     int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "app_id"                 int4                                        NOT NULL DEFAULT 0,
    "type"                   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "version"                varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "graph"                  text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "features"               text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "environment_variables"  text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '[]'::text,
    "conversation_variables" text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "create_by"              int4                                        NOT NULL DEFAULT 1,
    "create_time"            timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "workflows_publish_history_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."workflows_publish_history"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."workflows_publish_history"."id" IS '主键ID，自增整数';

COMMENT ON COLUMN "public"."workflows_publish_history"."app_id" IS '应用ID';

COMMENT ON COLUMN "public"."workflows_publish_history"."type" IS '工作流类型 (workflow/chat)';

COMMENT ON COLUMN "public"."workflows_publish_history"."version" IS '版本 (draft/具体版本号)';

COMMENT ON COLUMN "public"."workflows_publish_history"."graph" IS '工作流图配置 (JSON)';

COMMENT ON COLUMN "public"."workflows_publish_history"."features" IS '功能特性配置 (JSON)';

COMMENT ON COLUMN "public"."workflows_publish_history"."environment_variables" IS '环境变量 (JSON)';

COMMENT ON COLUMN "public"."workflows_publish_history"."conversation_variables" IS '对话变量 (JSON)';

COMMENT ON COLUMN "public"."workflows_publish_history"."create_by" IS '创建者ID';

COMMENT ON COLUMN "public"."workflows_publish_history"."create_time" IS '创建时间';

COMMENT ON TABLE "public"."workflows_publish_history" IS '工作流表，存储租户及应用的工作流配置';


CREATE TABLE "public"."workflows_experience"
(
    "id"                     int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "app_id"                 int4                                        NOT NULL DEFAULT 0,
    "type"                   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "graph"                  text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "features"               text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "environment_variables"  text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '[]'::text,
    "conversation_variables" text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "create_by"              int4                                        NOT NULL DEFAULT 1,
    "create_time"            timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "workflows_experience_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."workflows_experience"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."workflows_experience"."id" IS '主键ID，自增整数';

COMMENT ON COLUMN "public"."workflows_experience"."app_id" IS '应用ID';

COMMENT ON COLUMN "public"."workflows_experience"."type" IS '工作流类型 (workflow/chat)';

COMMENT ON COLUMN "public"."workflows_experience"."graph" IS '工作流图配置 (JSON)';

COMMENT ON COLUMN "public"."workflows_experience"."features" IS '功能特性配置 (JSON)';

COMMENT ON COLUMN "public"."workflows_experience"."environment_variables" IS '环境变量 (JSON)';

COMMENT ON COLUMN "public"."workflows_experience"."conversation_variables" IS '对话变量 (JSON)';

COMMENT ON COLUMN "public"."workflows_experience"."create_by" IS '创建者ID';

COMMENT ON COLUMN "public"."workflows_experience"."create_time" IS '创建时间';

COMMENT ON TABLE "public"."workflows_experience" IS '工作流表，存储租户及应用的工作流配置';

CREATE TABLE "public"."application_experience_tag"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "name"        varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "create_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_built_in" bool                                        NOT NULL DEFAULT false,
    CONSTRAINT "application_experience_tag_pkey" PRIMARY KEY ("id")
)
;
INSERT INTO "public"."application_experience_tag" ("name", "create_time", "update_time", "is_built_in")
VALUES ('快速上手', '2025-10-28 10:51:26.981795', '2025-10-28 10:51:26.981795', 't');
INSERT INTO "public"."application_experience_tag" ("name", "create_time", "update_time", "is_built_in")
VALUES ('热门精选', '2025-10-28 10:59:04.416754', '2025-10-28 10:59:04.416754', 't');


ALTER TABLE "public"."application_experience_tag"
    OWNER TO "postgres";

CREATE TABLE "public"."application_experience_tag_relation"
(
    "id"                        int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "tag_id"                    int4 NOT NULL DEFAULT 0,
    "experience_application_id" int4 NOT NULL DEFAULT 0,
    CONSTRAINT "application_experience_tag_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."application_experience_tag_relation"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."application_experience_tag_relation"."tag_id" IS '标签id';

COMMENT ON COLUMN "public"."application_experience_tag_relation"."experience_application_id" IS '应用id';