/**
  新增模型表
 */
CREATE TABLE "public"."model"
(
    "id"                  int4                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "name"                varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "type"                int2                                         NOT NULL DEFAULT 0,
    "classification"      int2                                         NOT NULL DEFAULT 1,
    "url"                 varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "icon_url"            varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "path"                varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "options"             jsonb                                        NOT NULL DEFAULT '[]'::jsonb,
    "introduction"        varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "unique_info"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "loading_mode"        varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "timbre_name"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "timbre_text"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "context_length"      int4                                         NOT NULL DEFAULT 0,
    "token_max"           int4                                         NOT NULL DEFAULT 0,
    "overview"            varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "usage_scene"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "local_deploy"        varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "api_document"        varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "is_support_visual"   bool                                         NOT NULL DEFAULT false,
    "is_support_document" bool                                         NOT NULL DEFAULT false,
    "is_support_function" bool                                         NOT NULL DEFAULT false,
    "is_support_adjust"   bool                                         NOT NULL DEFAULT false,
    "is_shelf"            bool                                         NOT NULL DEFAULT false,
    "create_by"           int4                                         NOT NULL DEFAULT 1,
    "update_by"           int4                                         NOT NULL DEFAULT 1,
    "create_time"         timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"         timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model"."name" IS '模型名称';

COMMENT
ON COLUMN "public"."model"."type" IS '模型类型 0：算法模型；1：预训练模型';

COMMENT
ON COLUMN "public"."model"."classification" IS '模型分类 1：文本生成；2：多模态；4：视频生成；5：图片生成；6：向量模型；7：语音合成；8：语音识别；9：排序模型；';

COMMENT
ON COLUMN "public"."model"."url" IS '模型调用地址';

COMMENT
ON COLUMN "public"."model"."icon_url" IS '图标地址';

COMMENT
ON COLUMN "public"."model"."path" IS '模型上传地址';

COMMENT
ON COLUMN "public"."model"."options" IS '模型配置';

COMMENT
ON COLUMN "public"."model"."introduction" IS '模型简介';

COMMENT
ON COLUMN "public"."model"."unique_info" IS '模型唯一信息';

COMMENT
ON COLUMN "public"."model"."loading_mode" IS '加载方式';

COMMENT
ON COLUMN "public"."model"."timbre_name" IS '音色名称';

COMMENT
ON COLUMN "public"."model"."timbre_text" IS '音色默认文本';

COMMENT
ON COLUMN "public"."model"."context_length" IS '模型上下文长度';

COMMENT
ON COLUMN "public"."model"."token_max" IS '最大tokens上限';

COMMENT
ON COLUMN "public"."model"."overview" IS '模型概述';

COMMENT
ON COLUMN "public"."model"."usage_scene" IS '应用场景';

COMMENT
ON COLUMN "public"."model"."local_deploy" IS '本地部署';

COMMENT
ON COLUMN "public"."model"."api_document" IS 'API调用文档';

COMMENT
ON COLUMN "public"."model"."is_support_visual" IS '是否支持视觉';

COMMENT
ON COLUMN "public"."model"."is_support_document" IS '是否支持文档';

COMMENT
ON COLUMN "public"."model"."is_support_function" IS '是否支持函数';

COMMENT
ON COLUMN "public"."model"."is_support_adjust" IS '是否支持微调';

COMMENT
ON COLUMN "public"."model"."is_shelf" IS '是否上架';

COMMENT
ON COLUMN "public"."model"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model" IS '模型';


/**
 新增模型分类表
 */
CREATE TABLE "public"."model_category"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE  1
        MAXVALUE 2147483647
        START 1
        CACHE 1
),
    "name"        varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character
        varying,
    "is_built"    bool                                        NOT NULL DEFAULT false,
    "create_by"   int4                                        NOT NULL DEFAULT 1,
    "update_by"   int4                                        NOT NULL DEFAULT 1,
    "create_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_category_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model_category"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model_category"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model_category"."name" IS '模型名称';

COMMENT
ON COLUMN "public"."model_category"."is_built" IS '是否预设';

COMMENT
ON COLUMN "public"."model_category"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model_category"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model_category"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model_category"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model_category" IS '模型分类';


/**
 新增模型标签表
 */
CREATE TABLE "public"."model_tag"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE  1
        MAXVALUE 2147483647
        START 1
        CACHE 1
),
    "category_id" int4                                        NOT NULL DEFAULT 0,
    "name"        varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"   int4                                        NOT NULL DEFAULT 1,
    "update_by"   int4                                        NOT NULL DEFAULT 1,
    "create_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_tag_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model_tag"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model_tag"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model_tag"."category_id" IS '分类id';

COMMENT
ON COLUMN "public"."model_tag"."name" IS '标签名称';

COMMENT
ON COLUMN "public"."model_tag"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model_tag"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model_tag"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model_tag"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model_tag" IS '模型标签';


/**
 新增模型-标签关系
 */
CREATE TABLE "public"."model_tag_relation"
(
    "id"          int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE  1
        MAXVALUE 2147483647
        START 1
        CACHE 1
),
    "category_id" int4         NOT NULL DEFAULT 0,
    "tag_id"      int4         NOT NULL DEFAULT 0,
    "model_id"    int4         NOT NULL DEFAULT 0,
    "create_by"   int4         NOT NULL DEFAULT 1,
    "update_by"   int4         NOT NULL DEFAULT 1,
    "create_time" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_tag_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model_tag_relation"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model_tag_relation"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model_tag_relation"."category_id" IS '分类id';

COMMENT
ON COLUMN "public"."model_tag_relation"."tag_id" IS '标签id';

COMMENT
ON COLUMN "public"."model_tag_relation"."model_id" IS '模型id';

COMMENT
ON COLUMN "public"."model_tag_relation"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model_tag_relation"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model_tag_relation"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model_tag_relation"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model_tag_relation" IS '模型-标签关系';


/**
 新增分类初始化数据
 */
INSERT INTO "public"."model_category" ("name", "is_built", "create_by", "update_by",
                                       "create_time", "update_time")
VALUES ('模型类型', true, 1, 1, '2025-06-03 17:04:43', '2025-06-03 17:05:01');

SELECT setval(pg_get_serial_sequence('model_category', 'id'),
              (SELECT MAX(id) FROM model_category));



