CREATE TABLE "public"."workflow_node_executions"
(
    "id"                  int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "tenant_id"           varchar(36) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "app_id"              int4                                        NOT NULL DEFAULT 0,
    "workflow_id"         int4                                        NOT NULL DEFAULT 0,
    "triggered_from"      varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "workflow_run_id"     varchar(36) COLLATE "pg_catalog"."default",
    "index"               int4                                        NOT NULL,
    "predecessor_node_id" varchar(36) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "node_execution_id"   varchar(36) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "node_id"             varchar(36) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "node_type"           varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "title"               varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "inputs"              text COLLATE "pg_catalog"."default"                  DEFAULT '{}'::text,
    "process_data"        text COLLATE "pg_catalog"."default"                  DEFAULT '{}'::text,
    "outputs"             text COLLATE "pg_catalog"."default"                  DEFAULT '{}'::text,
    "status"              varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "error"               text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT ''::text,
    "elapsed_time"        float8                                      NOT NULL DEFAULT 0,
    "execution_metadata"  text COLLATE "pg_catalog"."default"                  DEFAULT '{}'::text,
    "create_time"         timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at"         timestamp(6),
    "created_by_role"     varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "created_by"          int4                                        NOT NULL DEFAULT 1,
    CONSTRAINT "workflow_node_executions_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."workflow_node_executions"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."workflow_node_executions"."id" IS '主键ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."tenant_id" IS '租户ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."app_id" IS '应用ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."workflow_id" IS '工作流ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."triggered_from" IS '触发来源';

COMMENT ON COLUMN "public"."workflow_node_executions"."workflow_run_id" IS '工作流运行ID（单节点运行时为NULL）';

COMMENT ON COLUMN "public"."workflow_node_executions"."index" IS '执行序号';

COMMENT ON COLUMN "public"."workflow_node_executions"."predecessor_node_id" IS '前置节点ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."node_execution_id" IS '节点执行ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."node_id" IS '节点ID';

COMMENT ON COLUMN "public"."workflow_node_executions"."node_type" IS '节点类型（如：start, llm, tool等）';

COMMENT ON COLUMN "public"."workflow_node_executions"."title" IS '节点标题';

COMMENT ON COLUMN "public"."workflow_node_executions"."inputs" IS '输入参数（JSON格式）';

COMMENT ON COLUMN "public"."workflow_node_executions"."process_data" IS '处理数据（JSON格式）';

COMMENT ON COLUMN "public"."workflow_node_executions"."outputs" IS '输出结果（JSON格式）';

COMMENT ON COLUMN "public"."workflow_node_executions"."status" IS '执行状态（running/succeeded/failed/exception/retry）';

COMMENT ON COLUMN "public"."workflow_node_executions"."error" IS '错误信息';

COMMENT ON COLUMN "public"."workflow_node_executions"."elapsed_time" IS '执行耗时（秒）';

COMMENT ON COLUMN "public"."workflow_node_executions"."execution_metadata" IS '执行元数据（JSON格式）';

COMMENT ON COLUMN "public"."workflow_node_executions"."create_time" IS '创建时间，默认当前时间';

COMMENT ON COLUMN "public"."workflow_node_executions"."finished_at" IS '完成时间';

COMMENT ON COLUMN "public"."workflow_node_executions"."created_by_role" IS '创建者角色（account/end_user）';

COMMENT ON COLUMN "public"."workflow_node_executions"."created_by" IS '创建者ID';

COMMENT ON TABLE "public"."workflow_node_executions" IS '工作流节点运行';