-- 创建图谱可视化管理表
CREATE TABLE "public"."knowledge_graph_visual_manage"
(
    "visual_id"     int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "space_id"      int4                                        NOT NULL DEFAULT 0,
    "entity_name"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "centre_vertex" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "entity_id"     varchar(32) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "deleted"       bool                                        NOT NULL DEFAULT false,
    "create_by"     int4                                        NOT NULL DEFAULT 1,
    "update_by"     int4                                        NOT NULL DEFAULT 1,
    "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "knowledge_graph_visual_manage_pkey" PRIMARY KEY ("visual_id")
)
;

ALTER TABLE "public"."knowledge_graph_visual_manage"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."visual_id" IS '主键id';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."space_id" IS '知识库id';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."entity_name" IS '中心节点名称';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."centre_vertex" IS '中心点名称';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."entity_id" IS 'vertex ID';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."knowledge_graph_visual_manage" IS '图谱可视化管理';