-- 创建图知识库graph_pattern_tag
CREATE TABLE "public"."knowledge_graph_pattern_tag"
(

    "pattern_tag_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "space_id"      int4                                        NOT NULL DEFAULT 0,
    "tag_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"     int4                                        NOT NULL DEFAULT 1,
    "update_by"     int4                                        NOT NULL DEFAULT 1,
    "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"       bool                                        NOT NULL DEFAULT false,
    CONSTRAINT "knowledge_graph_pattern_tag_pkey" PRIMARY KEY ("pattern_tag_id")
)
;

ALTER TABLE "public"."knowledge_graph_pattern_tag"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_tag"."pattern_tag_id" IS '';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_tag"."space_id" IS '知识库id';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_tag"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_tag"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_tag"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_tag"."update_time" IS '更新时间';



----------------------------------------------------------------

-- graph_pattern_edge
CREATE TABLE "public"."knowledge_graph_pattern_edge"
(

    "pattern_edge_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "space_id"      int4                                        NOT NULL DEFAULT 0,
    "source_value" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "target_value" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "value" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"     int4                                        NOT NULL DEFAULT 1,
    "update_by"     int4                                        NOT NULL DEFAULT 1,
    "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"       bool                                        NOT NULL DEFAULT false,
    CONSTRAINT "knowledge_graph_pattern_edge_pkey" PRIMARY KEY ("pattern_edge_id")
)
;

ALTER TABLE "public"."knowledge_graph_pattern_edge"
    OWNER TO "postgres";


COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."space_id" IS '知识库id';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."source_value" IS '起始本体';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."target_value" IS '目标本体';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."target_value" IS '目标本体';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."value" IS '边属性名';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_edge"."update_time" IS '更新时间';

----------------------------------------------------------------


-- knowledge_graph_pattern_manager
CREATE TABLE "public"."knowledge_graph_pattern_manager"
(

    "manager_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "space_id"      int4                                        NOT NULL DEFAULT 0,
    "is_flush"      int2                                        NOT NULL DEFAULT 0,
    "create_by"     int4                                        NOT NULL DEFAULT 1,
    "update_by"     int4                                        NOT NULL DEFAULT 1,
    "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamp(0)                                NULL DEFAULT NULL,
    "deleted"       bool                                        NOT NULL DEFAULT false,
    CONSTRAINT "knowledge_graph_pattern_manager_pkey" PRIMARY KEY ("manager_id")
)
;

ALTER TABLE "public"."knowledge_graph_pattern_manager"
    OWNER TO "postgres";


COMMENT
ON COLUMN "public"."knowledge_graph_pattern_manager"."space_id" IS '知识库id';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_manager"."is_flush" IS '是否刷新，0表示未刷新，1表示已刷新';


COMMENT
ON COLUMN "public"."knowledge_graph_pattern_manager"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_graph_pattern_manager"."update_time" IS '更新时间';

----------------------------------------------------------------
-- 修改 chunk_content 列的数据类型为 text
ALTER TABLE "public"."knowledge_chunk_information"
ALTER COLUMN "chunk_content" TYPE text;

-- 设置 text 类型的默认值为空字符串
ALTER TABLE "public"."knowledge_chunk_information"
ALTER COLUMN "chunk_content" SET DEFAULT '';

-----------------------------------------------------
-- 修改 job_id 列：允许 NULL 值并设置默认值为 NULL
ALTER TABLE public.knowledge_chunk_information
ALTER COLUMN job_id DROP NOT NULL,
ALTER COLUMN job_id SET DEFAULT NULL;




