-- 创建知识库本体关系表
CREATE TABLE "public"."knowledge_graph_tag_edge"
(
    "tag_edge_id"  int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "space_id"     int4                                        NOT NULL DEFAULT 0,
    "type"         int2                                        NOT NULL DEFAULT 0,
    "tag_name"     varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "description"  varchar(125) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "ttl_col"      varchar(40) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "ttl_duration" int4                                        NOT NULL DEFAULT 0,
    "deleted"      bool                                        NOT NULL DEFAULT false,
    "create_by"    int4                                        NOT NULL DEFAULT 1,
    "update_by"    int4                                        NOT NULL DEFAULT 1,
    "create_time"  timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"  timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "knowledge_graph_tag_edge_pkey" PRIMARY KEY ("tag_edge_id")
)
;

ALTER TABLE "public"."knowledge_graph_tag_edge"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."tag_edge_id" IS '主键id';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."space_id" IS '知识库id';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."type" IS '类型  0：Tag；1：Edge';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."tag_name" IS '名称';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."description" IS '描述';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."ttl_col" IS 'ttlCol 字段';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."ttl_duration" IS '过期时间（小时为单位）';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."knowledge_graph_tag_edge" IS '图知识库本体关系';


-- 创建知识库本体关系属性表
CREATE TABLE "public"."knowledge_graph_tag_edge_property"
(
    "property_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "tag_edge_id"   int4                                        NOT NULL DEFAULT 0,
    "type"          int2                                        NOT NULL DEFAULT 0,
    "property_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "property_type" varchar(512) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "extra"         varchar(30) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "tag_required"  int2                                        NOT NULL DEFAULT 0,
    "default_value" text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '':: character varying,
    "deleted"       bool                                        NOT NULL DEFAULT false,
    "create_by"     int4                                        NOT NULL DEFAULT 1,
    "update_by"     int4                                        NOT NULL DEFAULT 1,
    "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "knowledge_graph_tag_edge_property_pkey" PRIMARY KEY ("property_id")
)
;

ALTER TABLE "public"."knowledge_graph_tag_edge_property"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."property_id" IS '主键id';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."tag_edge_id" IS 'Tag/Edge id';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."type" IS '类型  0：Tag；1：Edge';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."property_name" IS '名称';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."property_type" IS '属性类型';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."extra" IS '额外信息';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."tag_required" IS '是否必填：0：必填；1：不必填';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."default_value" IS '默认值';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_graph_tag_edge_property"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."knowledge_graph_tag_edge_property" IS '图知识库本体关系属性';