CREATE TABLE "public"."application"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "type"        varchar(50) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "name"        varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "icon_url"    varchar(300) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "status"      int2                                        NOT NULL DEFAULT 0,
    "create_by"   int4                                        NOT NULL DEFAULT 1,
    "update_by"   int4                                        NOT NULL DEFAULT 1,
    "create_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "application_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."application"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."application"."type" IS '应用类型---智能体agent,工作流应用workflow,智能体编排应用agent_arrangement';

COMMENT ON COLUMN "public"."application"."name" IS '应用名称';

COMMENT ON COLUMN "public"."application"."description" IS '描述';

COMMENT ON COLUMN "public"."application"."icon_url" IS '图标地址';

COMMENT ON COLUMN "public"."application"."status" IS '状态  -1删除，0草稿，1已发布';

COMMENT ON COLUMN "public"."application"."create_by" IS '创建人';

COMMENT ON COLUMN "public"."application"."update_by" IS '更新人';

COMMENT ON COLUMN "public"."application"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."application"."update_time" IS '更新时间';





CREATE TABLE "public"."application_tag"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "name"        varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "create_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "application_tag_pkey" PRIMARY KEY ("id")
)
;





CREATE TABLE "public"."application_tag_relation"
(
    "id"             int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "tag_id"         int4 NOT NULL DEFAULT 0,
    "application_id" int4 NOT NULL DEFAULT 0,
    CONSTRAINT "application_tag_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."application_tag_relation"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."application_tag_relation"."tag_id" IS '标签id';

COMMENT ON COLUMN "public"."application_tag_relation"."application_id" IS '应用id';




