CREATE TABLE "public"."upload_files"
(
    "id"           int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "tenant_id"    varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "storage_type" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "key"          varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "name"         varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "size"         int4                                        NOT NULL DEFAULT 0,
    "extension"    varchar(50) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "mime_type"    varchar(255) COLLATE "pg_catalog"."default",
    "used"         bool                                        NOT NULL DEFAULT false,
    "used_by"      int4,
    "used_at"      timestamp(6),
    "hash"         varchar(128) COLLATE "pg_catalog"."default",
    "source_url"   text COLLATE "pg_catalog"."default",
    "create_by"    int4                                        NOT NULL DEFAULT 1,
    "create_time"  timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "upload_files_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."upload_files"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."upload_files"."id" IS 'id';

COMMENT ON COLUMN "public"."upload_files"."tenant_id" IS '租户id';

COMMENT ON COLUMN "public"."upload_files"."storage_type" IS '存储类型';

COMMENT ON COLUMN "public"."upload_files"."key" IS '存储键值，在指定存储中的唯一路径或标识符';

COMMENT ON COLUMN "public"."upload_files"."name" IS '文件原始名称（包含扩展名）';

COMMENT ON COLUMN "public"."upload_files"."size" IS '大小';

COMMENT ON COLUMN "public"."upload_files"."extension" IS '文件扩展名';

COMMENT ON COLUMN "public"."upload_files"."mime_type" IS '文件MIME类型（例如 ''image/jpeg'', ''application/pdf''）';

COMMENT ON COLUMN "public"."upload_files"."used" IS '是否已被使用';

COMMENT ON COLUMN "public"."upload_files"."used_by" IS '使用者ID';

COMMENT ON COLUMN "public"."upload_files"."used_at" IS '使用时间';

COMMENT ON COLUMN "public"."upload_files"."hash" IS '文件内容哈希值（例如 MD5, SHA1, SHA256），用于校验和去重';

COMMENT ON COLUMN "public"."upload_files"."source_url" IS '文件来源URL（如果是从外部URL下载上传的）';

COMMENT ON COLUMN "public"."upload_files"."create_by" IS '创建者ID';

COMMENT ON COLUMN "public"."upload_files"."create_time" IS '创建时间';