CREATE TABLE "public"."document_config"
(
    "id"     int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "entity_prompt_require"             text                                         NOT NULL DEFAULT ''::text,
    "entity_prompt_other_require"       text                                         NOT NULL DEFAULT ''::text,
    "entity_prompt_output"              text                                         NOT NULL DEFAULT ''::text,
    "extract_entity_model"              varchar(100) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "document_id"                       int4                                         NOT NULL DEFAULT 0,
    "relation_prompt_require"           text                                         NOT NULL DEFAULT ''::text,
    "relation_prompt_other_require"     text                                         NOT NULL DEFAULT ''::text,
    "relation_prompt_output"            text                                         NOT NULL DEFAULT ''::text,
    "extract_relation_model"            varchar(100) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::text,
    "deleted"       bool                                        NOT NULL DEFAULT false,
    "create_by"     int4                                        NOT NULL DEFAULT 1,
    "update_by"     int4                                        NOT NULL DEFAULT 1,
    "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "document_config_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."document_config"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."document_config"."id" IS '主键id';

COMMENT
ON COLUMN "public"."document_config"."entity_prompt_require" IS '要求';

COMMENT
ON COLUMN "public"."document_config"."entity_prompt_other_require" IS '其他要求';

COMMENT
ON COLUMN "public"."document_config"."entity_prompt_output" IS '输出';

COMMENT
ON COLUMN "public"."document_config"."extract_entity_model" IS '大模型';


COMMENT
ON COLUMN "public"."document_config"."document_id" IS '文档id';

COMMENT
ON COLUMN "public"."document_config"."relation_prompt_require" IS '关系要求';

COMMENT
ON COLUMN "public"."document_config"."relation_prompt_other_require" IS '关系其他要求';

COMMENT
ON COLUMN "public"."document_config"."relation_prompt_output" IS '输出';

COMMENT
ON COLUMN "public"."document_config"."extract_relation_model" IS '大模型';


COMMENT
ON COLUMN "public"."document_config"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."document_config"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."document_config"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."document_config"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."document_config"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."document_config" IS '图谱可视化管理';

---------------------------------------

ALTER TABLE "public"."knowledge_chunk_information"
ALTER COLUMN "job_id" TYPE varchar(255) USING "job_id"::varchar(255),
ALTER COLUMN "job_id" SET DEFAULT '';

