CREATE TABLE "public"."application_key"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "app_id"      int4                                        NOT NULL DEFAULT 0,
    "user_id"     int4                                        NOT NULL DEFAULT 1,
    "key_value"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "create_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expire_time" timestamp(6)                                NOT NULL,
    CONSTRAINT "application_key_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."application_key"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."application_key"."id" IS 'id';

COMMENT ON COLUMN "public"."application_key"."app_id" IS '应用id';

COMMENT ON COLUMN "public"."application_key"."user_id" IS '应用所属人';

COMMENT ON COLUMN "public"."application_key"."key_value" IS '密钥';

COMMENT ON COLUMN "public"."application_key"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."application_key"."expire_time" IS '过期时间';

COMMENT ON TABLE "public"."application_key" IS '应用api_key';