/**
  数据集表
 */
CREATE TABLE "public"."model_dataset"
(
    "id"             int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "name"           varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "type"           int2                                        NOT NULL DEFAULT 0,
    "classification" int2                                        NOT NULL DEFAULT 1,
    "file_num"       int4                                        NOT NULL DEFAULT 0,
    "path"           varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "is_analysis"    int2                                        NOT NULL DEFAULT 0,
    "create_by"      int4                                        NOT NULL DEFAULT 1,
    "update_by"      int4                                        NOT NULL DEFAULT 1,
    "create_time"    timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_dataset_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model_dataset"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model_dataset"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model_dataset"."name" IS '数据集名称';

COMMENT
ON COLUMN "public"."model_dataset"."type" IS '数据集类型 0：训练数据；1：微调数据；2：评测数据';

COMMENT
ON COLUMN "public"."model_dataset"."classification" IS '模型分类 1：文本生成；2：多模态；4：视频生成；5：图片生成；6：向量模型；7：语音合成；8：语音识别；9：排序模型；';

COMMENT
ON COLUMN "public"."model_dataset"."file_num" IS '文件数量';

COMMENT
ON COLUMN "public"."model_dataset"."path" IS '文件路径';

COMMENT
ON COLUMN "public"."model_dataset"."is_analysis" IS '是否解析 0：否；1：是';

COMMENT
ON COLUMN "public"."model_dataset"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model_dataset"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model_dataset"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model_dataset"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model_dataset" IS '模型数据集';



/**
数据集文件表
 */
CREATE TABLE "public"."model_dataset_file"
(
    "id"          int4                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "dataset_id"  int4                                         NOT NULL DEFAULT 0,
    "name"        varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "size"        varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "path"        varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"   int4                                         NOT NULL DEFAULT 1,
    "update_by"   int4                                         NOT NULL DEFAULT 1,
    "create_time" timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_dataset_file_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model_dataset_file"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model_dataset_file"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model_dataset_file"."dataset_id" IS '数据集id';

COMMENT
ON COLUMN "public"."model_dataset_file"."name" IS '文件名称';

COMMENT
ON COLUMN "public"."model_dataset_file"."size" IS '文件大小';

COMMENT
ON COLUMN "public"."model_dataset_file"."path" IS '文件路径';

COMMENT
ON COLUMN "public"."model_dataset_file"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model_dataset_file"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model_dataset_file"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model_dataset_file"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model_dataset_file" IS '数据集文件';

/**
新增数据集id索引
 */
CREATE INDEX "dataset_id_index" ON "public"."model_dataset_file" USING btree (
    "dataset_id"
    );

COMMENT
ON INDEX "public"."dataset_id_index" IS '数据集id';