ALTER TABLE "public"."agent_long_term_memory"
    ADD COLUMN "data_type" varchar(255) NOT NULL DEFAULT 'draft';

COMMENT ON COLUMN "public"."agent_long_term_memory"."data_type" IS '数据类型  草稿draft，已发布published，试用experience';





CREATE TABLE "public"."application_experience"
(
    "id"                    int4                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "type"                  varchar(50) COLLATE "pg_catalog"."default"   NOT NULL DEFAULT ''::character varying,
    "name"                  varchar(100) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "description"           varchar(1000) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "icon_url"              varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "create_by"             int4                                         NOT NULL DEFAULT 1,
    "create_time"           timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "enable_workflow_trace" bool                                         NOT NULL DEFAULT false,
    "app_id"                int4                                         NOT NULL DEFAULT 0,
    CONSTRAINT "application_experience_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."application_experience"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."application_experience"."id" IS 'id';

COMMENT ON COLUMN "public"."application_experience"."type" IS '应用类型---智能体agent,工作流应用workflow,智能体编排应用agent_arrangement';

COMMENT ON COLUMN "public"."application_experience"."name" IS '应用名称';

COMMENT ON COLUMN "public"."application_experience"."description" IS '描述';

COMMENT ON COLUMN "public"."application_experience"."icon_url" IS '图标地址';

COMMENT ON COLUMN "public"."application_experience"."create_by" IS '创建人';

COMMENT ON COLUMN "public"."application_experience"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."application_experience"."enable_workflow_trace" IS '开启工作流追踪';

COMMENT ON COLUMN "public"."application_experience"."app_id" IS '应用id';

COMMENT ON TABLE "public"."application_experience" IS '应用-体验';