CREATE TABLE "public"."agent_info"
(
    "id"             int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "application_id" int4                                        NOT NULL DEFAULT 0,
    "prompt_words"   text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT ''::text,
    "model_id"       int4                                        NOT NULL DEFAULT 0,
    "model_name"     varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "create_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "agent_info_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_info"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_info"."id" IS 'id';

COMMENT ON COLUMN "public"."agent_info"."application_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_info"."prompt_words" IS '提示词';

COMMENT ON COLUMN "public"."agent_info"."model_id" IS '模型id';

COMMENT ON COLUMN "public"."agent_info"."model_name" IS '模型名称';

COMMENT ON COLUMN "public"."agent_info"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_info"."update_time" IS '更新时间';

COMMENT ON TABLE "public"."agent_info" IS '智能体信息';



CREATE TABLE "public"."agent_variable"
(
    "id"             int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "application_id" int4                                        NOT NULL DEFAULT 0,
    "field_type"     varchar(10) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT 'text'::character varying,
    "name"           varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "display_name"   varchar(50) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "select_options" text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT ''::text,
    "max_length"     int4                                        NOT NULL DEFAULT 0,
    "required"       bool                                        NOT NULL DEFAULT true,
    "create_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "agent_variable_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_variable"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_variable"."id" IS 'id';

COMMENT ON COLUMN "public"."agent_variable"."application_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_variable"."field_type" IS '字段类型--text文本,paragraph段落,select下拉选择，number数字';

COMMENT ON COLUMN "public"."agent_variable"."name" IS '变量名称';

COMMENT ON COLUMN "public"."agent_variable"."display_name" IS '显示名称';

COMMENT ON COLUMN "public"."agent_variable"."select_options" IS '下拉选项（逗号拼接）';

COMMENT ON COLUMN "public"."agent_variable"."max_length" IS '最大长度';

COMMENT ON COLUMN "public"."agent_variable"."required" IS '是否必填';

COMMENT ON COLUMN "public"."agent_variable"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_variable"."update_time" IS '更新时间';
COMMENT ON TABLE "public"."agent_variable" IS '智能体变量';