CREATE TABLE "public"."workflows"
(
    "id"                     int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "tenant_id"              varchar(32) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT ''::character varying,
    "app_id"                 int4                                        NOT NULL DEFAULT 0,
    "type"                   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "version"                varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "marked_name"            varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "marked_comment"         varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "graph"                  text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "features"               text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "environment_variables"  text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '[]'::text,
    "conversation_variables" text COLLATE "pg_catalog"."default"         NOT NULL DEFAULT '{}'::text,
    "create_by"              int4                                        NOT NULL DEFAULT 1,
    "create_time"            timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_by"              int4                                        NOT NULL DEFAULT 1,
    "update_time"            timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "workflows_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."workflows"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."workflows"."id" IS '主键ID，自增整数';

COMMENT ON COLUMN "public"."workflows"."tenant_id" IS '租户ID';

COMMENT ON COLUMN "public"."workflows"."app_id" IS '应用ID';

COMMENT ON COLUMN "public"."workflows"."type" IS '工作流类型 (workflow/chat)';

COMMENT ON COLUMN "public"."workflows"."version" IS '版本 (draft/具体版本号)';

COMMENT ON COLUMN "public"."workflows"."marked_name" IS '标记名称';

COMMENT ON COLUMN "public"."workflows"."marked_comment" IS '标记注释';

COMMENT ON COLUMN "public"."workflows"."graph" IS '工作流图配置 (JSON)';

COMMENT ON COLUMN "public"."workflows"."features" IS '功能特性配置 (JSON)';

COMMENT ON COLUMN "public"."workflows"."environment_variables" IS '环境变量 (JSON)';

COMMENT ON COLUMN "public"."workflows"."conversation_variables" IS '对话变量 (JSON)';

COMMENT ON COLUMN "public"."workflows"."create_by" IS '创建者ID';

COMMENT ON COLUMN "public"."workflows"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."workflows"."update_by" IS '更新者ID';

COMMENT ON COLUMN "public"."workflows"."update_time" IS '更新时间';

COMMENT ON TABLE "public"."workflows" IS '工作流表，存储租户及应用的工作流配置';