ALTER TABLE "public"."application_key"
    ADD COLUMN "last_use_time" timestamp(6);
COMMENT ON COLUMN "public"."application_key"."last_use_time" IS '上次使用时间';



ALTER TABLE "public"."application"
    ADD COLUMN "api_accessable" bool NOT NULL DEFAULT true;
COMMENT ON COLUMN "public"."application"."api_accessable" IS 'api是否可访问';


ALTER TABLE "public"."application"
    ADD COLUMN "url_accessable" bool         NOT NULL DEFAULT false,
    ADD COLUMN "url_key"        varchar(300) NOT NULL DEFAULT '';
COMMENT ON COLUMN "public"."application"."url_accessable" IS 'URL是否可访问';
COMMENT ON COLUMN "public"."application"."url_key" IS 'URL地址中的key';


ALTER TABLE "public"."application"
    ADD COLUMN "url_api_key_id" int4 NOT NULL DEFAULT 0;

COMMENT ON COLUMN "public"."application"."url_api_key_id" IS 'url绑定的api key的id';



COMMENT ON COLUMN "public"."application_key"."user_id" IS 'key创建人';



CREATE TABLE "public"."agent_chat_history"
(
    "id"                 int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "app_id"             int4                                        NOT NULL DEFAULT 0,
    "url_key"            varchar(300) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "conversation_title" varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "conversation_token" varchar(500) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "create_time"        timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"        timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "agent_id"           int4                                        NOT NULL DEFAULT 0,
    "chat_history"       jsonb                                       NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT "agent_chat_history_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_chat_history"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_chat_history"."id" IS 'id';

COMMENT ON COLUMN "public"."agent_chat_history"."app_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_chat_history"."url_key" IS 'url key';

COMMENT ON COLUMN "public"."agent_chat_history"."conversation_title" IS '对话标题';

COMMENT ON COLUMN "public"."agent_chat_history"."conversation_token" IS '对话token';

COMMENT ON COLUMN "public"."agent_chat_history"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_chat_history"."update_time" IS '更新时间';

COMMENT ON COLUMN "public"."agent_chat_history"."agent_id" IS '智能体id';

COMMENT ON COLUMN "public"."agent_chat_history"."chat_history" IS '对话历史';

COMMENT ON TABLE "public"."agent_chat_history" IS '智能体对话历史';



CREATE TABLE "public"."agent_chat_token"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "token"       varchar(200) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "app_id"      int4                                        NOT NULL DEFAULT 0,
    "agent_id"    int4                                        NOT NULL DEFAULT 0,
    "create_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "url_key"     varchar(300) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT "agent_chat_token_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."agent_chat_token"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_chat_token"."id" IS 'id';

COMMENT ON COLUMN "public"."agent_chat_token"."token" IS 'token';

COMMENT ON COLUMN "public"."agent_chat_token"."app_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_chat_token"."agent_id" IS '智能体id';

COMMENT ON COLUMN "public"."agent_chat_token"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_chat_token"."url_key" IS 'url key';

COMMENT ON TABLE "public"."agent_chat_token" IS '智能体url对话token';

ALTER TABLE "public"."agent_chat_token"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."agent_chat_token"."id" IS 'id';

COMMENT ON COLUMN "public"."agent_chat_token"."token" IS 'token';

COMMENT ON COLUMN "public"."agent_chat_token"."app_id" IS '应用id';

COMMENT ON COLUMN "public"."agent_chat_token"."agent_id" IS '智能体id';

COMMENT ON COLUMN "public"."agent_chat_token"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."agent_chat_token"."url_key" IS 'url key';

COMMENT ON TABLE "public"."agent_chat_token" IS '智能体url对话token';