-- 评测模型
CREATE TABLE "public"."eval_model"
(
    "id"                           int4                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "name"                         varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "type"                         int2                                         NOT NULL DEFAULT 0,
    "original_name"                varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "classification"               int2                                         NOT NULL DEFAULT 1,
    "url"                          varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "icon_url"                     varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "path"                         varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "options"                      jsonb                                        NOT NULL DEFAULT '[]'::jsonb,
    "introduction"                 varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "unique_info"                  varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "loading_mode"                 varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "timbre_name"                  varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "timbre_text"                  varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "context_length"               int4                                         NOT NULL DEFAULT 0,
    "token_max"                    int4                                         NOT NULL DEFAULT 0,
    "overview"                     varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "usage_scene"                  varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "local_deploy"                 varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "api_document"                 varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "is_support_visual"            bool                                         NOT NULL DEFAULT false,
    "is_support_document"          bool                                         NOT NULL DEFAULT false,
    "is_support_function"          bool                                         NOT NULL DEFAULT false,
    "is_support_adjust"            bool                                         NOT NULL DEFAULT false,
    "train_status"                 int2                                         NOT NULL DEFAULT 0,
    "reason"                       varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"                    int4                                         NOT NULL DEFAULT 1,
    "update_by"                    int4                                         NOT NULL DEFAULT 1,
    "create_time"                  timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"                  timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "internal_name"                varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "is_support_distributed_train" bool                                         NOT NULL DEFAULT false,
    "train_frame"                  varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT 'PyTorch':: character varying,
    "config_text"                  text COLLATE "pg_catalog"."default"          NOT NULL DEFAULT ''::text,
    "dataset_id"                   int4                                         NOT NULL DEFAULT 0,
    "cpu_cores_num"                int4                                         NOT NULL DEFAULT 0,
    "memory_size"                  int4                                         NOT NULL DEFAULT 0,
    "is_selected_gpu"              bool                                         NOT NULL DEFAULT false,
    "gpu_num"                      int4                                         NOT NULL DEFAULT 0,
    "task_id"                      varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "code_dir"                     varchar(512) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "code_url"                     varchar(512) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "is_deploy"                    bool                                         NOT NULL DEFAULT false,
    CONSTRAINT "eval_model_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."eval_model" OWNER TO "postgres";

COMMENT
ON COLUMN "public"."eval_model"."id" IS '主键id';

SELECT setval('"public"."eval_model_id_seq"', 1, false);

COMMENT
ON COLUMN "public"."eval_model"."name" IS '模型名称';

COMMENT
ON COLUMN "public"."eval_model"."type" IS '模型类型 0：算法模型；1：预训练模型';

COMMENT
ON COLUMN "public"."eval_model"."original_name" IS '模型原名称';

COMMENT
ON COLUMN "public"."eval_model"."classification" IS '模型分类 1：文本生成；2：多模态；4：视频生成；5：图片生成；6：向量模型；7：语音合成；8：语音识别；9：排序模型；';

COMMENT
ON COLUMN "public"."eval_model"."url" IS '模型调用地址';

COMMENT
ON COLUMN "public"."eval_model"."icon_url" IS '图标地址';

COMMENT
ON COLUMN "public"."eval_model"."path" IS '模型上传地址';

COMMENT
ON COLUMN "public"."eval_model"."options" IS '模型配置';

COMMENT
ON COLUMN "public"."eval_model"."introduction" IS '模型简介';

COMMENT
ON COLUMN "public"."eval_model"."unique_info" IS '模型唯一信息';

COMMENT
ON COLUMN "public"."eval_model"."loading_mode" IS '加载方式';

COMMENT
ON COLUMN "public"."eval_model"."timbre_name" IS '音色名称';

COMMENT
ON COLUMN "public"."eval_model"."timbre_text" IS '音色默认文本';

COMMENT
ON COLUMN "public"."eval_model"."context_length" IS '模型上下文长度';

COMMENT
ON COLUMN "public"."eval_model"."token_max" IS '最大tokens上限';

COMMENT
ON COLUMN "public"."eval_model"."overview" IS '模型概述';

COMMENT
ON COLUMN "public"."eval_model"."usage_scene" IS '应用场景';

COMMENT
ON COLUMN "public"."eval_model"."local_deploy" IS '本地部署';

COMMENT
ON COLUMN "public"."eval_model"."api_document" IS 'API调用文档';

COMMENT
ON COLUMN "public"."eval_model"."is_support_visual" IS '是否支持视觉';

COMMENT
ON COLUMN "public"."eval_model"."is_support_document" IS '是否支持文档';

COMMENT
ON COLUMN "public"."eval_model"."is_support_function" IS '是否支持函数';

COMMENT
ON COLUMN "public"."eval_model"."is_support_adjust" IS '是否支持微调';

COMMENT
ON COLUMN "public"."eval_model"."train_status" IS '训练状态：0：训练中；1：排队中；2：评测成功；3：评测失败；';

COMMENT
ON COLUMN "public"."eval_model"."reason" IS '失败原因';

COMMENT
ON COLUMN "public"."eval_model"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."eval_model"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."eval_model"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."eval_model"."update_time" IS '更新时间';

COMMENT
ON COLUMN "public"."eval_model"."internal_name" IS '模型内部名称';

COMMENT
ON COLUMN "public"."eval_model"."is_support_distributed_train" IS '是否支持分布式训练';

COMMENT
ON COLUMN "public"."eval_model"."train_frame" IS '分布式训练框架';

COMMENT
ON COLUMN "public"."eval_model"."config_text" IS '配置文件脚本';

COMMENT
ON COLUMN "public"."eval_model"."dataset_id" IS '数据集id';

COMMENT
ON COLUMN "public"."eval_model"."cpu_cores_num" IS 'CPU核数';

COMMENT
ON COLUMN "public"."eval_model"."memory_size" IS '内存（MB）';

COMMENT
ON COLUMN "public"."eval_model"."is_selected_gpu" IS '是否选择GPU';

COMMENT
ON COLUMN "public"."eval_model"."gpu_num" IS 'GPU块数';

COMMENT
ON COLUMN "public"."eval_model"."task_id" IS '任务id';

COMMENT
ON COLUMN "public"."eval_model"."code_dir" IS '解压后模型代码文件';

COMMENT
ON COLUMN "public"."eval_model"."code_url" IS '模型代码文件';

COMMENT
ON COLUMN "public"."eval_model"."is_deploy" IS '是否部署';

COMMENT
ON TABLE "public"."eval_model" IS '评测模型';


-- 评测模型分类
CREATE TABLE "public"."eval_model_category"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "name"        varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "is_built"    bool                                        NOT NULL DEFAULT false,
    "create_by"   int4                                        NOT NULL DEFAULT 1,
    "update_by"   int4                                        NOT NULL DEFAULT 1,
    "create_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "eval_model_category_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."eval_model_category" OWNER TO "postgres";

COMMENT
ON COLUMN "public"."eval_model_category"."id" IS '主键id';

SELECT setval('"public"."eval_model_category_id_seq"', 1, false);

COMMENT
ON COLUMN "public"."eval_model_category"."name" IS '模型分类名称';

COMMENT
ON COLUMN "public"."eval_model_category"."is_built" IS '是否预设';

COMMENT
ON COLUMN "public"."eval_model_category"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."eval_model_category"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."eval_model_category"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."eval_model_category"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."eval_model_category" IS '评测模型分类';


-- 评测模型标签
CREATE TABLE "public"."eval_model_tag"
(
    "id"               int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "eval_category_id" int4                                        NOT NULL DEFAULT 0,
    "name"             varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"        int4                                        NOT NULL DEFAULT 1,
    "update_by"        int4                                        NOT NULL DEFAULT 1,
    "create_time"      timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"      timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "eval_model_tag_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."eval_model_tag" OWNER TO "postgres";

COMMENT
ON COLUMN "public"."eval_model_tag"."id" IS '主键id';

SELECT setval('"public"."eval_model_tag_id_seq"', 1, false);

COMMENT
ON COLUMN "public"."eval_model_tag"."eval_category_id" IS '分类id';

COMMENT
ON COLUMN "public"."eval_model_tag"."name" IS '标签名称';

COMMENT
ON COLUMN "public"."eval_model_tag"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."eval_model_tag"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."eval_model_tag"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."eval_model_tag"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."eval_model_tag" IS '评测模型标签';


-- 评测模型-标签关系
CREATE TABLE "public"."eval_model_tag_relation"
(
    "id"               int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "eval_category_id" int4         NOT NULL DEFAULT 0,
    "eval_tag_id"      int4         NOT NULL DEFAULT 0,
    "eval_model_id"    int4         NOT NULL DEFAULT 0,
    "create_by"        int4         NOT NULL DEFAULT 1,
    "update_by"        int4         NOT NULL DEFAULT 1,
    "create_time"      timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"      timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "eval_model_tag_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."eval_model_tag_relation" OWNER TO "postgres";

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."id" IS '主键id';

SELECT setval('"public"."eval_model_tag_relation_id_seq"', 1, false);

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."eval_category_id" IS '分类id';

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."eval_tag_id" IS '标签id';

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."eval_model_id" IS '模型id';

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."eval_model_tag_relation"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."eval_model_tag_relation" IS '评测模型-标签关系';



INSERT INTO "public"."eval_model_category" ("name", "is_built", "create_by", "update_by",
                                                "create_time", "update_time")
VALUES ('模型类型', 't', 1, 1, now(), now());
INSERT INTO "public"."eval_model_category" ("name", "is_built", "create_by", "update_by",
                                                "create_time", "update_time")
VALUES ('标签', 'f', 1, 1, now(), now());
