CREATE TABLE "public"."train_model"
(
    "id"                  int4                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "name"                varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "original_name"       varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "classification"      int2                                         NOT NULL DEFAULT 1,
    "url"                 varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "icon_url"            varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "path"                varchar(300) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "options"             jsonb                                        NOT NULL DEFAULT '[]'::jsonb,
    "introduction"        varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "unique_info"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "loading_mode"        varchar(128) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "timbre_name"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "timbre_text"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "context_length"      int4                                         NOT NULL DEFAULT 0,
    "token_max"           int4                                         NOT NULL DEFAULT 0,
    "overview"            varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "usage_scene"         varchar(255) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "local_deploy"        varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "api_document"        varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "is_support_visual"   bool                                         NOT NULL DEFAULT false,
    "is_support_document" bool                                         NOT NULL DEFAULT false,
    "is_support_function" bool                                         NOT NULL DEFAULT false,
    "is_support_adjust"   bool                                         NOT NULL DEFAULT false,
    "train_status"        int2                                         NOT NULL DEFAULT 0,
    "train_path"          varchar(512) COLLATE "pg_catalog"."default"  NOT NULL DEFAULT '':: character varying,
    "reason"              varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"           int4                                         NOT NULL DEFAULT 1,
    "update_by"           int4                                         NOT NULL DEFAULT 1,
    "create_time"         timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"         timestamp(0)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "train_model_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."train_model"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."train_model"."id" IS '主键id';

COMMENT
ON COLUMN "public"."train_model"."name" IS '模型名称';

COMMENT
ON COLUMN "public"."train_model"."original_name" IS '模型原名称';

COMMENT
ON COLUMN "public"."train_model"."classification" IS '模型分类 1：文本生成；2：多模态；4：视频生成；5：图片生成；6：向量模型；7：语音合成；8：语音识别；9：排序模型；';

COMMENT
ON COLUMN "public"."train_model"."url" IS '模型调用地址';

COMMENT
ON COLUMN "public"."train_model"."icon_url" IS '图标地址';

COMMENT
ON COLUMN "public"."train_model"."path" IS '模型上传地址';

COMMENT
ON COLUMN "public"."train_model"."options" IS '模型配置';

COMMENT
ON COLUMN "public"."train_model"."introduction" IS '模型简介';

COMMENT
ON COLUMN "public"."train_model"."unique_info" IS '模型唯一信息';

COMMENT
ON COLUMN "public"."train_model"."loading_mode" IS '加载方式';

COMMENT
ON COLUMN "public"."train_model"."timbre_name" IS '音色名称';

COMMENT
ON COLUMN "public"."train_model"."timbre_text" IS '音色默认文本';

COMMENT
ON COLUMN "public"."train_model"."context_length" IS '模型上下文长度';

COMMENT
ON COLUMN "public"."train_model"."token_max" IS '最大tokens上限';

COMMENT
ON COLUMN "public"."train_model"."overview" IS '模型概述';

COMMENT
ON COLUMN "public"."train_model"."usage_scene" IS '应用场景';

COMMENT
ON COLUMN "public"."train_model"."local_deploy" IS '本地部署';

COMMENT
ON COLUMN "public"."train_model"."api_document" IS 'API调用文档';

COMMENT
ON COLUMN "public"."train_model"."is_support_visual" IS '是否支持视觉';

COMMENT
ON COLUMN "public"."train_model"."is_support_document" IS '是否支持文档';

COMMENT
ON COLUMN "public"."train_model"."is_support_function" IS '是否支持函数';

COMMENT
ON COLUMN "public"."train_model"."is_support_adjust" IS '是否支持微调';

COMMENT
ON COLUMN "public"."train_model"."train_status" IS '训练状态：0：训练中；1：排队中；2：训练成功；3：训练失败；';

COMMENT
ON COLUMN "public"."train_model"."train_path" IS '模型训练的地址';

COMMENT
ON COLUMN "public"."train_model"."reason" IS '失败原因';

COMMENT
ON COLUMN "public"."train_model"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."train_model"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."train_model"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."train_model"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."train_model" IS '训练模型';



/**
训练模型分类表
 */
CREATE TABLE "public"."train_model_category"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "name"        varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "is_built"    bool                                        NOT NULL DEFAULT false,
    "create_by"   int4                                        NOT NULL DEFAULT 1,
    "update_by"   int4                                        NOT NULL DEFAULT 1,
    "create_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "train_model_category_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."train_model_category"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."train_model_category"."id" IS '主键id';

COMMENT
ON COLUMN "public"."train_model_category"."name" IS '训练的模型分类名称';

COMMENT
ON COLUMN "public"."train_model_category"."is_built" IS '是否预设';

COMMENT
ON COLUMN "public"."train_model_category"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."train_model_category"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."train_model_category"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."train_model_category"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."train_model_category" IS '训练模型分类';


/**
训练模型标签表
 */
CREATE TABLE "public"."train_model_tag"
(
    "id"                int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "train_category_id" int4                                        NOT NULL DEFAULT 0,
    "name"              varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "create_by"         int4                                        NOT NULL DEFAULT 1,
    "update_by"         int4                                        NOT NULL DEFAULT 1,
    "create_time"       timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"       timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "train_model_tag_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."train_model_tag"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."train_model_tag"."id" IS '主键id';

COMMENT
ON COLUMN "public"."train_model_tag"."train_category_id" IS '分类id';

COMMENT
ON COLUMN "public"."train_model_tag"."name" IS '标签名称';

COMMENT
ON COLUMN "public"."train_model_tag"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."train_model_tag"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."train_model_tag"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."train_model_tag"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."train_model_tag" IS '训练模型标签';


/**
训练模型-标签关系
 */
CREATE TABLE "public"."train_model_tag_relation"
(
    "id"                int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "train_category_id" int4         NOT NULL DEFAULT 0,
    "train_tag_id"      int4         NOT NULL DEFAULT 0,
    "train_model_id"    int4         NOT NULL DEFAULT 0,
    "create_by"         int4         NOT NULL DEFAULT 1,
    "update_by"         int4         NOT NULL DEFAULT 1,
    "create_time"       timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"       timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "train_model_tag_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."train_model_tag_relation"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."train_model_tag_relation"."id" IS '主键id';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."train_category_id" IS '分类id';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."train_tag_id" IS '标签id';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."train_model_id" IS '训练的模型id';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."train_model_tag_relation"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."train_model_tag_relation" IS '训练模型-标签关系';


/* 初始化训练模型分类数据 */
INSERT INTO "public"."train_model_category" ("name", "is_built", "create_by", "update_by",
                                             "create_time", "update_time")
VALUES ('模型类型', 't', 1, 1, now(), now());

INSERT INTO "public"."train_model_category" ("name", "is_built", "create_by", "update_by",
                                             "create_time", "update_time")
VALUES ('标签', 'f', 1, 1, now(), now());

SELECT setval(pg_get_serial_sequence('train_model_category', 'id'),
              (SELECT MAX(id) FROM train_model_category));