CREATE TABLE "public"."mcp"
(
    "id"            int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "display_name"  varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "internal_name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "description"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "params"        jsonb                                       NOT NULL DEFAULT '{}'::jsonb,
    "mcp_icon_url"  varchar(500) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "is_shelf"      bool                                        NOT NULL,
    "create_time"   timestamp(6)                                NOT NULL,
    "update_time"   timestamp(6)                                NOT NULL,
    "url"           varchar(300) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT "mcp_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mcp"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."mcp"."id" IS 'id';

COMMENT ON COLUMN "public"."mcp"."display_name" IS 'mcp名称';

COMMENT ON COLUMN "public"."mcp"."internal_name" IS 'mcp内部名称';

COMMENT ON COLUMN "public"."mcp"."description" IS '描述';

COMMENT ON COLUMN "public"."mcp"."params" IS '参数';

COMMENT ON COLUMN "public"."mcp"."mcp_icon_url" IS 'mcp图标路径';

COMMENT ON COLUMN "public"."mcp"."is_shelf" IS '是否上架';

COMMENT ON COLUMN "public"."mcp"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."mcp"."update_time" IS '更新时间';

COMMENT ON COLUMN "public"."mcp"."url" IS 'mcp url';

COMMENT ON TABLE "public"."mcp" IS 'mcp';



CREATE TABLE "public"."mcp_tag"
(
    "id"          int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "name"        varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "create_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "mcp_tag_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mcp_tag"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."mcp_tag"."id" IS '主键id';

COMMENT ON COLUMN "public"."mcp_tag"."name" IS '标签名称';

COMMENT ON COLUMN "public"."mcp_tag"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."mcp_tag"."update_time" IS '更新时间';



CREATE TABLE "public"."mcp_tag_relation"
(
    "id"          int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "mcp_id"      int4         NOT NULL DEFAULT 0,
    "tag_id"      int4         NOT NULL DEFAULT 0,
    "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "mcp_tag_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mcp_tag_relation"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."mcp_tag_relation"."id" IS 'id';

COMMENT ON COLUMN "public"."mcp_tag_relation"."mcp_id" IS 'mcp id';

COMMENT ON COLUMN "public"."mcp_tag_relation"."tag_id" IS '标签id';

COMMENT ON COLUMN "public"."mcp_tag_relation"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."mcp_tag_relation"."update_time" IS '更新时间';

COMMENT ON TABLE "public"."mcp_tag_relation" IS 'mcp和标签关联';



CREATE TABLE "public"."mcp_application_relation"
(
    "id"             int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "mcp_id"         int4         NOT NULL DEFAULT 0,
    "application_id" int4         NOT NULL DEFAULT 0,
    "create_time"    timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "mcp_application_relation_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mcp_application_relation"
    OWNER TO "postgres";

COMMENT ON COLUMN "public"."mcp_application_relation"."id" IS 'id';

COMMENT ON COLUMN "public"."mcp_application_relation"."mcp_id" IS 'mcp id';

COMMENT ON COLUMN "public"."mcp_application_relation"."application_id" IS '应用id';

COMMENT ON COLUMN "public"."mcp_application_relation"."create_time" IS '创建时间';

COMMENT ON COLUMN "public"."mcp_application_relation"."update_time" IS '更新时间';

COMMENT ON TABLE "public"."mcp_application_relation" IS 'mcp和应用关联';