CREATE TABLE "public"."knowledge_extraction" (

            "extraction_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
        "job_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "space_id" int4                                        NOT NULL DEFAULT 0,
        "space_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "tag_names" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "edge_names" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "type"          smallint                                    NOT NULL  DEFAULT 0,
        "deleted"       bool                                        NOT NULL DEFAULT false,
        "create_by"     int4                                        NOT NULL DEFAULT 1,
        "update_by"     int4                                        NOT NULL DEFAULT 1,
        "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP


);


ALTER TABLE "public"."knowledge_extraction"
    OWNER TO "postgres";


COMMENT
ON COLUMN "public"."knowledge_extraction"."extraction_id" IS '知识抽取ID';

COMMENT
ON COLUMN "public"."knowledge_extraction"."job_name" IS '任务名称';

COMMENT
ON COLUMN "public"."knowledge_extraction"."space_id" IS '图空间ID';

COMMENT
ON COLUMN "public"."knowledge_extraction"."space_name" IS '图空间名称';

COMMENT
ON COLUMN "public"."knowledge_extraction"."tag_names" IS '本体名称,以,分割';

COMMENT
ON COLUMN "public"."knowledge_extraction"."edge_names" IS '关系名称,以,分割';

COMMENT
ON COLUMN "public"."knowledge_graph_visual_manage"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_extraction"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_extraction"."create_by" IS '创建人ID';

COMMENT
ON COLUMN "public"."knowledge_extraction"."update_time" IS '更新时间';

COMMENT
ON COLUMN "public"."knowledge_extraction"."update_by" IS '更新人ID';

COMMENT
ON COLUMN "public"."knowledge_extraction"."type" IS '0 实体类型任务，1文档类型任务';



----------------------------------------------------------

CREATE TABLE "public"."knowledge_document_information" (

         "document_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
             INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
         "extraction_id" int4                                        NOT NULL DEFAULT 0,
         "document_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
         "total_pages"   int4                                        NOT NULL DEFAULT 0,
         "file_path"     varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
         "file_format"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
         "analysis"      smallint                                    NOT NULL DEFAULT 0,
         "document_status"   int4                                    NOT NULL DEFAULT 0,
         "chunk_size"    int4                                        NOT NULL DEFAULT 0,
         "job_id"   int4                                             NOT NULL DEFAULT 0,
         "deleted"       bool                                        NOT NULL DEFAULT false,
         "create_by"     int4                                        NOT NULL DEFAULT 1,
         "update_by"     int4                                        NOT NULL DEFAULT 1,
         "create_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
         "update_time"   timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."knowledge_document_information"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_document_information"."document_id" IS '文档ID';

COMMENT
ON COLUMN "public"."knowledge_document_information"."extraction_id" IS '关联抽取任务id';

COMMENT
ON COLUMN "public"."knowledge_document_information"."document_name" IS '文档名称';

COMMENT
ON COLUMN "public"."knowledge_document_information"."total_pages" IS '总页数';

COMMENT
ON COLUMN "public"."knowledge_document_information"."file_path" IS '文件路径';

COMMENT
ON COLUMN "public"."knowledge_document_information"."file_format" IS '文件格式';

COMMENT
ON COLUMN "public"."knowledge_document_information"."analysis" IS '是否抽取，0表示未抽取，1表示已抽取';

COMMENT
ON COLUMN "public"."knowledge_document_information"."document_status" IS '抽取状态';

COMMENT
ON COLUMN "public"."knowledge_document_information"."chunk_size" IS 'chunk总数量';

COMMENT
ON COLUMN "public"."knowledge_document_information"."job_id" IS '解析文件任务id';

COMMENT
ON COLUMN "public"."knowledge_document_information"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_document_information"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_document_information"."create_by" IS '创建人ID';

COMMENT
ON COLUMN "public"."knowledge_document_information"."update_time" IS '更新时间';

COMMENT
ON COLUMN "public"."knowledge_document_information"."update_by" IS '更新人ID';


----------------------------------------------------------


CREATE TABLE "public"."knowledge_document_verification" (

            "verification_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
        "document_id"           int4                                        NOT NULL DEFAULT 0,
        "chunk_id"              int4                                        NOT NULL DEFAULT 0,
        "subject"               varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "subject_tag_name"      varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "edge_type"             varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "object"                varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "object_tag_name"       varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "type"                  smallint                                    NOT NULL  DEFAULT 0,
        "verification_status"   smallint                                    NOT NULL  DEFAULT 0,
        "property_type"         varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
        "deleted"               bool                                        NOT NULL DEFAULT false,
        "create_by"             int4                                        NOT NULL DEFAULT 1,
        "update_by"             int4                                        NOT NULL DEFAULT 1,
        "create_time"           timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "update_time"           timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP

);


ALTER TABLE "public"."knowledge_document_verification"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_document_verification"."verification_id" IS '文档校验 id';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."document_id" IS '所属文档ID';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."chunk_id" IS 'chunk id';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."subject" IS '主体类型';

COMMENT
ON COLUMN "public"."knowledge_document_verification".subject_tag_name IS '主体名称';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."edge_type" IS '关系/属性';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."object" IS '主体类型';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."type" IS '关系属性，0表示关系，1表述属性';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."verification_status" IS '校验状态，0初始状态，1表示已校验,2已入图';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."property_type" IS '解析文件任务id';


COMMENT
ON COLUMN "public"."knowledge_document_verification"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_document_verification"."update_time" IS '更新时间';


-------------------------------------------------------



CREATE TABLE "public"."knowledge_chunk_information" (

          "chunk_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
              INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
          "document_id"           int4                                        NOT NULL DEFAULT 0,
          "chunk_content"         varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
          "job_id"                int4                                        NOT NULL DEFAULT 0,
          "chunk_status"          int4                                        NOT NULL DEFAULT 0,
          "chunk_index"           int4                                        NOT NULL DEFAULT 0,
          "page_number"           int4                                        NOT NULL DEFAULT 0,
          "sheet_name"            varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
          "deleted"               bool                                        NOT NULL DEFAULT false,
          "create_by"             int4                                        NOT NULL DEFAULT 1,
          "update_by"             int4                                        NOT NULL DEFAULT 1,
          "create_time"           timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
          "update_time"           timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP

);


ALTER TABLE "public"."knowledge_chunk_information"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."chunk_id" IS 'chunk id';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."document_id" IS '所属文档ID';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."chunk_content" IS '文本内容';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."job_id" IS '任务id  用于删除后取消任务';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."chunk_status" IS 'chunk 状态  0 未抽取 1 抽取完成';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."page_number" IS '在原文中的页码';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."chunk_index" IS '序号';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."sheet_name" IS 'sheet 名称';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."deleted" IS '是否删除 false 否 true 删除';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."knowledge_chunk_information"."update_time" IS '更新时间';

-----------------------------------------------


CREATE TABLE "public"."knowledge_sheet_information" (

                    "sheet_id"   int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                        INCREMENT 1
            MINVALUE  1
            MAXVALUE 2147483647
            START 1
            CACHE 1
            ),
          "document_id"           int4                                        NOT NULL DEFAULT 0,
          "sheet_name"         varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying

);


ALTER TABLE "public"."knowledge_sheet_information"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."knowledge_sheet_information"."sheet_id" IS 'sheet_id';

COMMENT
ON COLUMN "public"."knowledge_sheet_information"."document_id" IS '所属文档ID';

COMMENT
ON COLUMN "public"."knowledge_sheet_information"."sheet_name" IS 'sheet_name';
