CREATE TABLE "public"."model_api_key"
(
    "id"             int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "model_id"       int4                                        NOT NULL DEFAULT 0,
    "secret"         varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '':: character varying,
    "last_used_time" timestamp(0)                                         DEFAULT NULL:: timestamp without time zone,
    "create_by"      int4                                        NOT NULL DEFAULT 1,
    "update_by"      int4                                        NOT NULL DEFAULT 1,
    "create_time"    timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamp(0)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "model_api_key_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."model_api_key"
    OWNER TO "postgres";

COMMENT
ON COLUMN "public"."model_api_key"."id" IS '主键id';

COMMENT
ON COLUMN "public"."model_api_key"."model_id" IS '模型id';

COMMENT
ON COLUMN "public"."model_api_key"."secret" IS '密钥';

COMMENT
ON COLUMN "public"."model_api_key"."last_used_time" IS '最后使用时间';

COMMENT
ON COLUMN "public"."model_api_key"."create_by" IS '创建人';

COMMENT
ON COLUMN "public"."model_api_key"."update_by" IS '更新人';

COMMENT
ON COLUMN "public"."model_api_key"."create_time" IS '创建时间';

COMMENT
ON COLUMN "public"."model_api_key"."update_time" IS '更新时间';

COMMENT
ON TABLE "public"."model_api_key" IS '模型密钥';