CREATE TABLE "public"."knowledge_base_application_relation"
(
    "id"             int4                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        ),
    "application_id" int4                                        NOT NULL DEFAULT 0,
    "knowledge_base_id"       int4                                        NOT NULL DEFAULT 0,
    "create_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "knowledge_base_application_relation_pkey" PRIMARY KEY ("id")
)
;
